### ISSUE TITLE
关于标题栏右边图标的问题

### ISSUE THREAD

**Issue by lichao315** [getActivity/TitleBar#1]
你好！请问能不能再丰富一下效果，就是标题栏右边图标，有时候ui设计是可以同时放两个可点击的icon的。对于这种情况，是否可以继续完善支持一下。
非常感谢！

**Comment by 880634** [comment]
这种效果很少见，右边一般只有一个。建议你自定义布局，代码如下：

            <com.hjq.bar.TitleBar
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="20dp">

                <LinearLayout
                    android:gravity="end"
                    android:orientation="horizontal"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">

                    <ImageView
                        android:src="@mipmap/ic_launcher"
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent" />
                    
                    <ImageView
                        android:src="@mipmap/ic_launcher"
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent" />

                </LinearLayout>

            </com.hjq.bar.TitleBar>
