### ISSUE TITLE
是否支持subTitle的扩展

### ISSUE THREAD

**Issue by suzhonxia** [getActivity/TitleBar#12]

**Comment by getActivity** [comment]
当然可以，不过需要这样实现

            <com.hjq.bar.TitleBar
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="20dp"
                android:background="@mipmap/title_bar_head"
                app:barStyle="transparent"
                app:title="自定义TitleBar">

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:gravity="center"
                    android:orientation="vertical">

                     

            </com.hjq.bar.TitleBar>
