### ISSUE TITLE
TitleBar类的onMeasure应该不对吧

### ISSUE THREAD

**Issue by ljphawk** [getActivity/TitleBar#20]
// 设置TitleBar默认的宽度
        if (MeasureSpec.getMode(heightMeasureSpec) == MeasureSpec.AT_MOST
                || MeasureSpec.getMode(heightMeasureSpec) == MeasureSpec.UNSPECIFIED) {
            widthMeasureSpec = MeasureSpec.makeMeasureSpec(widthMeasureSpec, MeasureSpec.EXACTLY);
        }

这里为什么是获取的高的测量模式

**Comment by ljphawk** [comment]
感谢提供思路，自己封装的时候改了下
 @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        // 设置TitleBar默认的宽度
        if (MeasureSpec.getMode(widthMeasureSpec) != MeasureSpec.EXACTLY) {
            widthMeasureSpec = MeasureSpec.makeMeasureSpec(widthMeasureSpec, MeasureSpec.EXACTLY);
        }
        // 设置TitleBar默认的高度
        if (MeasureSpec.getMode(heightMeasureSpec) != MeasureSpec.EXACTLY) {
            //内容最大的高度
            int contentMaxHeight;
            contentMaxHeight = getActionBarHeight();
            final Drawable background = getBackground();
            // 如果当前背景是一张图片的话
            if (background instanceof BitmapDrawable) {
                // 算出标题栏的宽度和图片的宽度之比例
                final double ratio = (double) MeasureSpec.getSize(widthMeasureSpec) / (double) background.getIntrinsicWidth();
                //取最大的一个
                contentMaxHeight = Math.max((int) (ratio * background.getIntrinsicHeight()), contentMaxHeight);
            }
            int childCount = getChildCount();
            for (int i = 0; i < childCount; i++) {
                View childAt = getChildAt(i);
                //如果view是gone掉的或者第0个 （第0个是toolbar,高度不需要比较,固定写得match_parent）
                if (childAt.getVisibility() == View.GONE || i == 0) {
                    continue;
                }
                //测量子view的宽高
                measureChild(childAt, widthMeasureSpec, heightMeasureSpec);
                contentMaxHeight = Math.max(contentMaxHeight, childAt.getMeasuredHeight());
            }
            heightMeasureSpec = MeasureSpec.makeMeasureSpec(contentMaxHeight, MeasureSpec.EXACTLY);
            getLayoutParams().height = MeasureSpec.getSize(heightMeasureSpec);
        }
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }

**Comment by getActivity** [comment]
多谢小伙子的建议
