### ISSUE TITLE
constraintlayout中返回键点击失效。

### ISSUE THREAD

**Issue by alanzyz** [getActivity/TitleBar#22]
案例使用androidx，并使用constraintlayout, 点击返回键，无反应。

**Comment by getActivity** [comment]
你必须在 Activity 基类中设置点击事件，TitleBar 不负责设置点击事件，具体实现可以看 Demo

**Comment by alanzyz** [comment]
我的问题，布局采用androidx constraintlayout 复写，复写的时候为组件添加了id。 那边没有用此新id。

**Comment by alanzyz** [comment]
抱歉
