### ISSUE TITLE
返回按钮怎么在BaseActivity统一finish处理

### ISSUE THREAD

**Issue by MyChanges** [getActivity/TitleBar#23]

**Comment by getActivity** [comment]
可参考：https://github.com/getActivity/AndroidProject

**Comment by MyChanges** [comment]
您好，我抽空看了下您的项目，有个疑问，dialog封装部分，用了dialogfragment为什么还要用dialog




| |
钟鹏
|
|
邮箱：zhongpeng251827@163.com
|

签名由 网易邮箱大师 定制

在2019年10月11日 17:21，Android 轮子哥 写道：

Closed #23.

**Comment by MyChanges** [comment]
Test




| |
钟鹏
|
|
邮箱：zhongpeng251827@163.com
|

签名由 网易邮箱大师 定制

在2019年10月15日 11:43，MyChanges 写道：
您好，我抽空看了下您的项目，有个疑问，dialog封装部分，用了dialogfragment为什么还要用dialog




| |
钟鹏
|
|
邮箱：zhongpeng251827@163.com
|

签名由 网易邮箱大师 定制

在2019年10月11日 17:21，Android 轮子哥 写道：

Closed #23.

**Comment by MyChanges** [comment]
test

**Comment by palorotolo** [comment]
在哪一块也没看到呀

**Comment by getActivity** [comment]
@palorotolo [AppActivity.java](https://github.com/getActivity/AndroidProject/blob/master/app/src/main/java/com/hjq/demo/app/AppActivity.java)
