### ISSUE TITLE
兼容沉浸式状态栏：兼容Github的沉浸式状态栏框架，达到完全沉浸的效果

### ISSUE THREAD

**Issue by tdxtxt** [getActivity/TitleBar#25]
我是用的沉浸式状态栏三方是 https://github.com/gyf-dev/ImmersionBar
```
ImmersionBar.with(this).titleBar(view);//设置重叠问题
```
这里需要传入的view，TitleBar没有提供啊，怎么解决？

**Comment by getActivity** [comment]
直接传 TitleBar 对象进去就可以了

**Comment by tdxtxt** [comment]
看源码，并没有提供单独的view设置statusbar的高度，反而被ImmersionBar修改了整体高度了，如果不设置fitsSystemWindow属性，是无法沉浸的吧
