### ISSUE TITLE
文字样式

### ISSUE THREAD

**Issue by xiangxm** [getActivity/TitleBar#3]
有需求遇到：想设置标题栏文字的bold等样式，比如中间文字变大变粗。

**Comment by getActivity** [comment]
> 你好，字体大小可以通过以下方法`

- xml属性size_title进行设置

- 对象方法mTitleBar.getTitleView().setTextSize();

- 静态方法TitleBar.initStyle(new ITitleBarStyle());（全局有效）

> 字体加粗则可以通过

- 对象方法mTitleBar.getTitleView().setTypeface();（建议封装到基类中）

**Comment by xiangxm** [comment]
好的，多谢
