### ISSUE TITLE
希望 TitleBar 里面的子 view 能够垂直方向居中显示

### ISSUE THREAD

**Issue by ZQ173** [getActivity/TitleBar#33]
1、打比方，将高度设为 58dp，发现子 view 底部空了一部分，上下不会对称。
2、本库不错，感觉还可以应用于设置页面，不单单是标题，减少很多不必要的重复工作。
     为此，希望能增加属性设置分割线边距，能实现像微信一样，分割线左边有边距，右边充满。

**Comment by getActivity** [comment]
多谢建议，这个问题会在下个版本进行优化

**Comment by getActivity** [comment]
框架已经重构完成，关于标题栏高度的问题，新版本上面已经不是定死 58dp，而是通过设置子 View 的内边距来控制标题栏的高度。
