### ISSUE TITLE
viewpager2 套fragment，第一次切换titlebar高度跳动

### ISSUE THREAD

**Issue by shitb** [getActivity/TitleBar#36]
![555](https://user-images.githubusercontent.com/4415390/100815331-9aa59a80-347e-11eb-84ed-03aa8088b619.jpg)

**Comment by getActivity** [comment]
你用的是什么版本的框架

**Comment by getActivity** [comment]
麻烦上传一下关于这个问题的动图或者视频，光看描述我想象不到效果是什么样的

**Comment by shitb** [comment]
![1607006387061](https://user-images.githubusercontent.com/4415390/101043039-cdec4480-35b8-11eb-8642-1b744b72e922.gif)

布局代码
<img width="558" alt="截屏2020-12-03 下午10 43 30" src="https://user-images.githubusercontent.com/4415390/101043235-0c81ff00-35b9-11eb-97a0-cfd26a4ed16b.png">

适配器
<img width="706" alt="截屏2020-12-03 下午10 44 33" src="https://user-images.githubusercontent.com/4415390/101043305-24f21980-35b9-11eb-8098-5abe49c0bbc6.png">
@getActivity

**Comment by shitb** [comment]
框架都是最新的

**Comment by getActivity** [comment]
你这个问题是因为设置沉浸式状态栏的时机不对导致的

**Comment by getActivity** [comment]
你应该把设置沉浸式状态的时机放在 onViewCreated 方法里面，这样就不会有这个问题

**Comment by shitb** [comment]
> 你应该把设置沉浸式状态的时机放在 onViewCreated 方法里面，这样就不会有这个问题
 
完美，多谢大佬
