### ISSUE TITLE
建议左边布局加上默认销毁activity的事件

### ISSUE THREAD

**Issue by po1xiao** [getActivity/TitleBar#37]
左边返回按钮绝大多数情况下的功能是返回（个人认为），所以建议加上销毁activity事件，能减少很多Activit中的重复代码

**Comment by getActivity** [comment]
首先这个监听事件不应该是框架帮你写逻辑，而是应该由使用者来写逻辑，当然我从你的话里面能听出来，你应该是在每个 Activity 都有写这个监听，这种做法显然不是明智的，你可以把这个监听处理封装到基类中。

**Comment by getActivity** [comment]
如果你不知道怎么封装，可以参考这个开源项目：[https://github.com/getActivity/AndroidProject](https://github.com/getActivity/AndroidProject)

**Comment by po1xiao** [comment]
好的， 非常感谢
