### ISSUE TITLE
title会跳动

### ISSUE THREAD

**Issue by Chenshibiao** [getActivity/TitleBar#4]
样式为 【 left + title 】的时候（即没有设置右边的情况），第一次打开后title会从右边一点点跳到正中间，预览布局的时候title也是往右偏了一点的。每次都跳动很不好吧。谢谢大佬分享。

**Comment by getActivity** [comment]
因为内部使用了LinearLayout和权重，我使用延迟的形式来改善这个效果，所以会造成预览布局时的偏移，实际运行不会出现这种效果，不会影响开发使用。如果有更好的idea，欢迎你提交Pull
