### ISSUE TITLE
支持titlebar右边多个icon或多个文本按钮的形式么？

### ISSUE THREAD

**Issue by foxcode7** [getActivity/TitleBar#40]

**Comment by getActivity** [comment]
小伙子，不支持的，你只能自定义布局来实现

**Comment by getActivity** [comment]
因为 UI 框架是无法做到万能定制化的，我只能做最常用的那种方式，你要是不信可以克隆代码下来改成你想要的样子，你就会明白，此路通了，其他路又不通了。

**Comment by getActivity** [comment]
小伙子，还有其他问题不，没有的话我就关闭 issue 了。

**Comment by foxcode7** [comment]
木有了，感谢大佬耐心回复，可以关了。

**Comment by mtzqc** [comment]
val tv = titleBar?.currentInitializer?.getRightView(view!!.context) ?: return
            var lp = (tv.layoutParams as FrameLayout.LayoutParams)
            var dpx = SizeUtils.dp2px(15f)
            tv.setPadding(dpx, 0, dpx, 0)
            lp.rightMargin = dpx * 4
            tv.text = "按钮"
            titleBar!!.addView(tv)
            tv.onClick {
                toast("点击")
            }
