### ISSUE TITLE
切换到系统的暗黑模式下 右侧没有设置任何图标 显示有空白

### ISSUE THREAD

**Issue by NeVaDaAAA** [getActivity/TitleBar#43]
自定义配置如下:

class PetTitleBarStyle : CommonBarStyle() {

    override fun createBackgroundDrawable(context: Context): Drawable =
        ColorDrawable(context.getCol(R.color.white))

    override fun createBackIcon(context: Context?): Drawable =
        getDrawableResources(context, R.mipmap.ic_arrow_back_black)

    override fun createTitleView(context: Context): TextView {
        val titleTv = super.createTitleView(context)
        titleTv.setTextColor(context.getCol(R.color.title_text))
        titleTv.setTextSize(TypedValue.COMPLEX_UNIT_SP, 17f)
        return titleTv
    }

    override fun createLeftView(context: Context): TextView {
        val leftView = super.createLeftView(context)
        leftView.setTextColor(context.getCol(R.color.white))
        setViewBackground(
            leftView, SelectorDrawable.Builder()
                .setDefault(ColorDrawable(context.getCol(R.color.white)))
                .setFocused(ColorDrawable(context.getCol(R.color.white)))
                .setPressed(ColorDrawable(context.getCol(R.color.white)))
                .build()
        )
        return leftView
    }

    override fun createRightView(context: Context): TextView {
        val rightView = super.createRightView(context)
        rightView.setTextColor(context.getCol(R.color.title_text))
        setViewBackground(
            rightView, SelectorDrawable.Builder()
                .setDefault(ColorDrawable(context.getCol(R.color.white)))
                .setFocused(ColorDrawable(context.getCol(R.color.white)))
                .setPressed(ColorDrawable(context.getCol(R.color.white)))
                .build()
        )
        return rightView
    }

    override fun createLineView(context: Context): View {
        val lineView = super.createLineView(context)
        setViewBackground(lineView, ColorDrawable(context.getCol(R.color.divider_color)))
        return lineView
    }
}

![2021610-101442](https://user-images.githubusercontent.com/20659340/121454053-b90fc400-c9d4-11eb-8e21-94248833afa1.jpeg)

**Comment by NeVaDaAAA** [comment]
机型为小米手机 miui12.5

**Comment by getActivity** [comment]
小伙子，你把代码发给我作用不大，我要能复现才能可以，但是你的源码总不可能发我吧？所以需要麻烦你下载 Demo源码进行复现，然后把复现步骤告诉我，又或者直接把修改完的 Demo 源码发给我。

**Comment by NeVaDaAAA** [comment]
轮子哥你好:
发现问题了 
 setViewBackground(
            rightView, SelectorDrawable.Builder()
                .setDefault(ColorDrawable(context.getCol(R.color.white)))
                .setFocused(ColorDrawable(context.getCol(R.color.white)))
                .setPressed(ColorDrawable(context.getCol(R.color.white)))
                .build()
        )
设置了右边的颜色 默认的标题栏(加上右icon不会) 在miui的暗黑模式下 右边就会出现白色空白 
如果不设置setViewBackground是OK的

**Comment by getActivity** [comment]
@NeVaDaAAA 小伙子，这句话代码本身有什么问题吗？

**Comment by getActivity** [comment]
miui 暗黑模式引发的这个问题，我刚开了一下暗黑模式，并没有发现该问题。

**Comment by getActivity** [comment]
@NeVaDaAAA 还有你如果想适配暗黑模式的话，按钮的背景色在暗黑模式下不应该是黑色的？我看你给我发的代码设置背景色为白色。

**Comment by NeVaDaAAA** [comment]
没有去适配暗黑模式... 就是今天开了手机的暗黑模式 发现了这个问题
