### ISSUE TITLE
建议扩展支持：头部右侧支持两个textview 

### ISSUE THREAD

**Issue by chenhao1041661180** [getActivity/TitleBar#46]
建议扩展支持：中间及右侧支持不同view样式
![image](https://user-images.githubusercontent.com/9623182/133357805-0c4bdb12-c3a9-4d05-b45c-901c5ad9ac02.png)
![image](https://user-images.githubusercontent.com/9623182/133357829-b823d0c2-0bf2-4235-8e6e-ef4114059f85.png)

建议右侧View能支持 两个TextView

**Comment by getActivity** [comment]
* 小伙子，你要明白一件事，UI 框架是无法满足所有需求的，只能针对常用的需求进行封装，你这种情况的话，建议你自定义布局来实现，而不是用 TitleBar 来实现。

**Comment by getActivity** [comment]
* TitleBar 并不是为了满足所有需求而诞生的，我的设计初衷是只针对一些常用的需求，例如左边中间右边各有一个 TextView 做封装，其他情况建议你自定义布局。至于为什么不为了满足所有需求而生，你可以想象一下，如果所有的需求都可以实现了，TitleBar 布局属性该怎么命名？然后还有一个问题，你要怎么让别人不用去记这些布局属性？

* 如果你觉得我说得不对，你可以尝试为下面这些需求设计一套新的框架出来，你就会明白我为什么要这么设计了。

    * 标题栏中间带个 Tab 切换的

    * 标题栏中间带个搜索框的

    * 标题栏左边带两个按钮的

    * 标题栏右边带两个按钮的

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
