### ISSUE TITLE
TitleBar嵌套在Toolbar中 导致titleBar中的箭头或标题靠下显示（不居中ToolBar）并且显示不全

### ISSUE THREAD

**Issue by 979881765** [getActivity/TitleBar#50]
## 问题描述

* 框架版本：XXX

* 问题描述：XXX

* 复现步骤：XXX

* 是否必现：填是/否

* 手机信息：例如某米 9 / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生 API 是否会出现该问题：是/否（排查一下是不是框架的代码写法存在问题导致的）

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，这个问题属于 ToolBar 的问题还是 TitleBar 的问题？

**Comment by 979881765** [comment]
在ToolBar中嵌套其他的layout组件后，layout中的组件可以居中。嵌套TitleBar 就不行了

**Comment by getActivity** [comment]
上代码，发截图

**Comment by 979881765** [comment]
代码：
     <androidx.appcompat.widget.Toolbar
                android:id="@+id/tb_task_title"
                android:layout_width="match_parent"
                android:layout_height="?android:attr/actionBarSize"
                android:background="@color/red"
                app:layout_collapseMode="pin">

                <com.hjq.bar.TitleBar
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:title="导航栏" />


            </androidx.appcompat.widget.Toolbar>

**Comment by 979881765** [comment]
- [ ]
![2141640153713_ pic](https://user-images.githubusercontent.com/17971668/147045774-5ca2a759-d5ca-4d29-aad3-8e1e5e1c8346.jpg)

**Comment by getActivity** [comment]
你为什么要把 TitleBar 放到 ToolBar 里面？

**Comment by 979881765** [comment]
ToolBar可以结合CollapsingToolbarLayout 实现固定在顶部，我为了统一使用titleBar 就把他嵌套在了ToolBar中，否则得单独添加返回按钮

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/147051100-28af6bcc-cdf1-4cac-9b92-7bb056bd6003.png)

**Comment by getActivity** [comment]
你可以参考一下 demo 怎么写的

**Comment by 979881765** [comment]
好的 懂了，demo是利用ToolBar做了个占位。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
