### ISSUE TITLE
标题栏左右两侧的图标或文本加入按下时的效果

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/TitleBar#52]
就像toolbar一样，按下时图标被圆形阴影覆盖，白夜模式是不同的阴影颜色，或者也可以设置阴影颜色属性

目前只有方形的效果，而且颜色有点淡

或者是像你的PressAlphaTextView工具类一样，让图标或者文本半透明

**Comment by getActivity** [comment]
关于这个是水波纹的效果，你可以自己看看 Toolbar 是怎么实现的，然后自己实现一下。

**Comment by SaltedFish-Extreme** [comment]
> 关于这个是水波纹的效果，你可以自己看看 Toolbar 是怎么实现的，然后自己实现一下。

我觉得按下效果应该是由框架来实现的，你的demo也说的完善细节追求完美🤔或者最起码开放个属性方法啥的，提供默认的效果还有可以自定义的效果，一般可以点击的控件需要水波纹效果只需要设置`android:foreground="?attr/selectableItemBackground"`就可以了，但是你这也没地方设置单独的点击效果😅

**Comment by getActivity** [comment]
[TitleBar-9.5.aar.zip](https://github.com/getActivity/TitleBar/files/8179235/TitleBar-9.5.aar.zip)

**Comment by getActivity** [comment]
@SaltedFish-Extreme 加入了 leftForeground 和 rightForeground 属性，因为是基于原生 API 去封装，所以只能在 Android 6.0 的设备上面才有效果。

**Comment by getActivity** [comment]
@SaltedFish-Extreme 另外这个 `?attr/selectableItemBackground` 属性值也可以设置给 background

**Comment by SaltedFish-Extreme** [comment]
@getActivity 话说这个aar包咋用啊，我复制到libs目录了，也在app模块下依赖里加入了，咋还报错没有这个类呢
![image](https://user-images.githubusercontent.com/54784104/156720898-68ff0aa4-d3e5-4bad-951d-e82613a25ba7.png)
![image](https://user-images.githubusercontent.com/54784104/156720918-b9863c1d-b740-4c49-bdaf-9faa716f85cc.png)
![image](https://user-images.githubusercontent.com/54784104/156720969-0159b4b2-73d3-449b-83fe-12a688872614.png)
![image](https://user-images.githubusercontent.com/54784104/156721002-58546133-16ef-4f18-b4ec-26e5d1455a75.png)

**Comment by SaltedFish-Extreme** [comment]
哦，我发现了，你给我的是个压缩包，我直接拖进去没解压，怪不得不显示😅

**Comment by SaltedFish-Extreme** [comment]
效果可以，麻烦你了😉

**Comment by SaltedFish-Extreme** [comment]
@getActivity 轮子哥，9.5啥时候发布依赖啊😋

**Comment by getActivity** [comment]
@SaltedFish-Extreme 短时间不会发布，你可以先用本地包依赖，效果都是一样的。

**Comment by SaltedFish-Extreme** [comment]
> @SaltedFish-Extreme 短时间不会发布，你可以先用本地包依赖，效果都是一样的。

好的🤗
