### ISSUE TITLE
字体样式只能代码设置么getTitleBar().getTitleView().setXXX()

### ISSUE THREAD

**Issue by ender115** [getActivity/TitleBar#53]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
是的。是2020年的，不知道现在修复没有
* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
字体样式只能代码设置么getTitleBar().getTitleView().setXXX()
* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/28616817/156865968-be6731d8-c7a6-4ca4-be44-39fb5a172dc5.png">

**Comment by SaltedFish-Extreme** [comment]
我觉得问题是问能不能在xml中设置，有titleStyle属性
![image](https://user-images.githubusercontent.com/54784104/156919801-42f658b9-8556-4b2c-ad6a-8988266d3bd5.png)
![image](https://user-images.githubusercontent.com/54784104/156919810-a042c1b7-7434-416a-9f7e-7465ab8ef2f0.png)
