### ISSUE TITLE
右边，文字与图标的点击事件怎么分别处理

### ISSUE THREAD

**Issue by yuandoudou928** [getActivity/TitleBar#54]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
否

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
点击事件，如果我右边有图标又有文字，他们的点击事件不一样，请问要怎么处理呢？

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
