### ISSUE TITLE
边距设置的建议

### ISSUE THREAD

**Issue by Samdogcom** [getActivity/TitleBar#55]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
* 无

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
* childPaddingHorizontal 同时控制了所有View的边距,调整左右边距时会影响到中间标题的边距

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
* 左中右3个View可以单独设置padding或者增加左右margin的参数,谢谢

**Comment by getActivity** [comment]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/28616817/165208234-16b6cb43-32b4-4d24-b0d8-44e359c66753.png">

**Comment by getActivity** [comment]
[TitleBar-9.5.aar.zip](https://github.com/getActivity/TitleBar/files/8559285/TitleBar-9.5.aar.zip)
