### ISSUE TITLE
框架中 TitleBar 类的方法注释中含有错别字

### ISSUE THREAD

**Issue by anjiemo** [getActivity/TitleBar#56]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】无

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】clearTitleIconTint、clearLeftIconTint、clearRightIconTint 这三个方法的注释有错别字。

* 你觉得该怎么去完善会比较好？【非必答】将方法注释从 “**清楚** 左标题的图标着色器” 修改为 “**清除** 左标题的图标着色器” （其余两处同理）。

**Comment by getActivity** [comment]
收到，多谢小伙子的提醒，问题已经纠正了，由于这个问题无伤大雅，会随着下个版本一起更新。

**Comment by anjiemo** [comment]
好的
