### ISSUE TITLE
OnTitleBarListener 接口的回调方法上需添加 不可空 注解，这对 kotlin 开发者将会很友好

### ISSUE THREAD

**Issue by anjiemo** [getActivity/TitleBar#57]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】无

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】OnTitleBarListener 接口的 onLeftClick、onTitleClick、onRightClick 方法参数未添加 不可空注解（@NoNull）。

* 你觉得该怎么去完善会比较好？【非必答】我查看了框架的源码，发现这几个回调方法的地方参数都为 TitleBar 类本身，不可能出现为 null 的情况，所以建议添加 **@NoNull** 注解修饰该参数，这样在 kotlin 开发者覆写这几个回调方法的时候 IDE 就不会识别为可空类型，开发者也不用去判空或者修改这个可空类型为不可空。这对 kotlin 开发者将会非常很友好。

**Comment by getActivity** [comment]
小伙子，经过认真思考，这个建议不给予采纳，具体原因如下：

1. `@NonNull` 注解需要添加 Support 或者 AndroidX 相关的依赖库才可以，这样会导致使用的人需要处理这两个库冲突的问题。

2. 加不加 `@NonNull` 注解都不影响在 Kotlin 的使用，Kotlin 针对  Java 方法中没有添加 `@NonNull` 注解的参数都会默认加上 `?`，如果你不喜欢 `?`，可以直接去除掉，这并不会导致编译报错。

**Comment by anjiemo** [comment]
okay，那么是否可以在接口注释上加以说明呢？  不然只能查看调用处才能知道这个参数是否为 `null`  ，如果加在接口注释上的话应该会比较方便一点。

**Comment by getActivity** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/28616817/192126323-6658d64a-8f57-466d-ad99-b89f4ccb37d9.png">

**Comment by getActivity** [comment]
@anjiemo 这个可以有，已经加上了，多谢建议。
