### ISSUE TITLE
设置左侧标题时，标题比较长的情况下，字体颜色失真，并且闪烁

### ISSUE THREAD

**Issue by qq570026938** [getActivity/TitleBar#58]
#### 问题描述

* 框架版本【必填】：9.5

* 问题描述【必填】：设置左侧标题时，标题比较长的情况下，字体颜色失真，并且闪烁

* 复现步骤【必填】：titleBar.leftTitle = “这里是标题哦”

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：所有手机都一样

* 出现问题的安卓版本【必填】：8.0

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：否，9.3版本的时候字数过多时显示不全，没有这个闪烁问题

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

* 使用原生的 FrameLayout 来实现是否也会出现该问题【非必答】：是/否（排查一下是不是框架的代码存在问题导致的）

**Comment by getActivity** [comment]
小伙子，请回答这个问题。

**Comment by qq570026938** [comment]
> 小伙子，请回答这个问题。
能复现

**Comment by qq570026938** [comment]
你在demo的 夜间模式的标题栏 这个设置lefttitle 长点的标题，很明显

**Comment by getActivity** [comment]
[TitleBar-9.6.aar.zip](https://github.com/getActivity/TitleBar/files/9943485/TitleBar-9.6.aar.zip)

**Comment by getActivity** [comment]
小伙子，经过核实，确实存在这个问题，目前问题已经修复了，你用这个包试试看。

**Comment by getActivity** [comment]
小伙子，远程依赖已经更新，你可以更新远程依赖后重试。

**Comment by qq570026938** [comment]
好的
