### ISSUE TITLE
标题栏中间带图标不带文字

### ISSUE THREAD

**Issue by xiangxm** [getActivity/TitleBar#6]
你好，现在有个需求是标题栏中间是图标，不设置文字，这个现在有方法吗？

**Comment by getActivity** [comment]
<com.hjq.bar.TitleBar
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <ImageView
                    android:layout_gravity="center"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:src="@mipmap/ic_launcher" />

            </com.hjq.bar.TitleBar>
