### ISSUE TITLE
10.0依赖下载不下来，10.2打包合并values.xml出现此错误，需要帮助

### ISSUE THREAD

**Issue by zangjy** [getActivity/TitleBar#61]
* 框架版本【必填】：10.2

* 问题描述【必填】：在新电脑上没有10.0的缓存，10.0版本的依赖下载不下来，使用10.2版本打包APK合并values.xml时出现错误，10.0版本是正常的，不知道该如何修改，需要您的帮助

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLewenReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file E:\WorkSpace\AndroidStudioWorkSpace\Tablet\app\build\intermediates\incremental\lewenRelease\mergeLewenReleaseResources\merged.dir\values\values.xml. Cause: java.nio.file.InvalidPathException: Illegal char <:> at index 49: com.sdym.tablet.app-mergeLewenReleaseResources-83:/values/values.xml). Check logs for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 16s
250 actionable tasks: 43 executed, 207 up-to-date
```

**Comment by zangjy** [comment]
不好意思，我该选择help wanted标签😅

**Comment by getActivity** [comment]
小伙子，我看到的是你现在有两个问题：

1. 10.0 框架的版本下载不下来的问题：我试过了，是可以下载的，你下载不下来应该是你的网络或者配置的问题，你可以直接从 [TitleBar/releases/10.2](https://github.com/getActivity/TitleBar/releases/10.2) 下载
2. 升级 10.2 报错的问题：这个问题应该是 View 的属性名冲突了，不过从你提供的报错信息没有看出来具体是什么问题，需要你提供更加详细的报错信息，又或者你自行解决。

**Comment by zangjy** [comment]
第一个问题已经解决了
第二个它没有更多的错误信息了，我再仔细检查一下我的项目吧
感谢回复

**Comment by devilived** [comment]
最后咋解决的？

**Comment by zangjy** [comment]
> 最后咋解决的？

我尝试了下升级到10.3，就没出现这个问题了，我没有修改任何东西

**Comment by ggyg123** [comment]
@getActivity 大佬，自定义的属性名改成唯一的吧，今天依赖也报这个错了，发现是titlesize,titlecolor这两个属性和项目中有冲突了

**Comment by getActivity** [comment]
@ggyg123 小伙子，跟什么项目冲突了？

**Comment by ggyg123** [comment]
@getActivity 项目依赖的module太多了，不确定跟哪个有冲突，后来把titlebar库下载下来copy到项目中，改了attr的titlesize和titlecolor的名字就好了
