### ISSUE TITLE
升级了10.2  titleTextEllipsize属性和CollapsingToolbarLayout的titleTextEllipsize 冲突

### ISSUE THREAD

**Issue by KONAPKU0** [getActivity/TitleBar#62]
![image](https://user-images.githubusercontent.com/21329140/232373791-027aa1c4-ffce-4aa4-b81f-73dc652f9eba.png)
![image](https://user-images.githubusercontent.com/21329140/232374030-4e156ba5-21aa-4bf5-a2f3-6f648d25b519.png)

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
