### ISSUE TITLE
[疑惑]：在 Application 初始化样式后，整个标题栏都可以触发左标题的点击事件

### ISSUE THREAD

**Issue by Keeeya** [getActivity/TitleBar#64]
### 问题描述【必填】

在Application 初始化样式，自定义样式TitleBarStyle继承CommonBarStyle，点击整个标题栏都触发左标题的点击事件，在标题栏添加属性app:leftBackground后发现，占满了整个标题栏，但是注释掉Application 中初始化的代码后，就左标题的大小就正常了

- Application 初始化样式

![image](https://github.com/getActivity/TitleBar/assets/73430635/cdb8b4d4-9439-41a6-8446-80579cb25c7f)

- 注释掉初始化代码

![image](https://github.com/getActivity/TitleBar/assets/73430635/5241715e-3bcd-442e-bdd8-b23e3f2bb0d6)

- xml里的代码
![image](https://github.com/getActivity/TitleBar/assets/73430635/fb9936bc-cc88-409a-bacb-264a3408b81c)

不确定是bug还是，老哥可以帮忙看一下嘛？？

### issue 是否有人曾提过类似的问题？【必答】

否

### 框架文档是否有提及到此问题？【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 不清楚问题是不是 Bug 的，一律按照 Bug 处理，所以不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
