### ISSUE TITLE
[Bug]：在 Application 初始化自定义样式后，整个标题栏都可以触发左标题的点击事件 

### ISSUE THREAD

**Issue by Keeeya** [getActivity/TitleBar#65]
### 框架版本【必填】

10.3

### 问题描述【必填】

在Application 初始化样式，自定义样式TitleBarStyle继承CommonBarStyle，点击整个标题栏都触发左标题的点击事件，在标题栏添加属性app:leftBackground后发现，占满了整个标题栏，但是注释掉Application 中初始化的代码后，就左标题的大小就正常了

- Application 初始化样式

![image](https://github.com/getActivity/TitleBar/assets/73430635/2a6c0d88-ab06-4b4c-8360-57e2c688bd89)

- 注释掉初始化代码
![image](https://github.com/getActivity/TitleBar/assets/73430635/fc15f056-0b76-4d6e-b5bf-add5872e6eb2)

- xml里的代码
![image](https://github.com/getActivity/TitleBar/assets/73430635/159d9efe-f160-4bc3-a3ee-8a101991a32c)

### 复现步骤【必填】

在 Application 初始化样式成自定义的样式

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

oppo findx2 pro、虚拟机Pixel

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

试过的上面两种机型都有

### 框架最新的版本是否存在这个问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 是否有人曾提过类似的问题【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

### 使用原生的 FrameLayout 来实现是否也会出现该问题【必答】

否

**Comment by getActivity** [comment]
小伙子，劳烦提供一个可供复现的 Demo 到这里来。

**Comment by getActivity** [comment]
@Keeeya 小伙子，你可以基于 Github 的 Demo 工程改成能复现你问题的样子，然后打包压缩上传到这里来。

**Comment by Keeeya** [comment]
> @Keeeya 小伙子，你可以基于 Github 的 Demo 工程改成能复现你问题的样子，然后打包压缩上传到这里来。

[test.zip](https://github.com/getActivity/TitleBar/files/11515902/test.zip)老哥你看一下这个demo

**Comment by getActivity** [comment]
[TitleBar-10.5.aar.zip](https://github.com/getActivity/TitleBar/files/11522433/TitleBar-10.5.aar.zip)

**Comment by getActivity** [comment]
小伙子，根据你提供的 Demo 工程，确实有该问题存在，我已经修正了这个问题，你下载上面的 aar 包测试看看问题还会不会出现？

**Comment by Keeeya** [comment]
> 小伙子，根据你提供的 Demo 工程，确实有该问题存在，我已经修正了这个问题，你下载上面的 aar 包测试看看问题还会不会出现？

arr包暂时没发现左标题占满的问题了，有发现再和老哥提。

- 不过还有一点就是

![image](https://github.com/getActivity/TitleBar/assets/73430635/7c457793-fb31-4af7-bb7e-9dab4da9af11)
为啥在TitleGravity的问题上要做出这种限制，在左右有图标文字 等 带有内容的时候，titleGravity=left或right就会失效

- 另外老哥有考虑过把  标题字体 和 icon 的点击事件分开出来吗

**Comment by getActivity** [comment]
https://github.com/getActivity/TitleBar/blob/master/library/src/main/java/com/hjq/bar/TitleBar.java#L938

**Comment by getActivity** [comment]
小伙子，你这个问题代码注释上面已经回答了。

**Comment by getActivity** [comment]
> 另外老哥有考虑过把 标题字体 和 icon 的点击事件分开出来吗

不会考虑，这样标题就从一个 View 变成了两个 View，加上这个场景会比较少，所以不会考虑做。

**Comment by Keeeya** [comment]
> 小伙子，你这个问题代码注释上面已经回答了。

就是说为什么要做出这种 ” 如果标题的重心为左右，那么左右就不能有内容“ 的限制

像这种标题靠靠左的场景不也是挺常见的吗？？
![image](https://github.com/getActivity/TitleBar/assets/73430635/488e3fd3-a039-4376-bf29-4fa2b5f287be)

如果说要把这种标题靠左的状况使用 leftTitle 来实现，那么点击这个 标题文字 也会触发左标题的点击事件，这样不会很奇怪吗？？

**Comment by getActivity** [comment]
这是因为 leftView、titleView、rightView 最终会被添加到 FrameLayout 中，而不是 LinearLayout 中，如果要达到你说的那种效果也不是不行，但是要改变 TitleBar 结构，使用自定义 ViewGroup 实现，这个后续可能会考虑做，但是目前暂时不考虑这样做。

**Comment by Keeeya** [comment]
好的，那10.5啥时候更新嘞

**Comment by getActivity** [comment]
@Keeeya 小伙子，可能没有那么快发布，你先上线，后面远程依赖发布了，你再换回来，当然测试过程要是有出现问题，也可以在这里反馈给我，我会保留这个 issue 一段时间。

**Comment by Keeeya** [comment]
> 
好滴，感谢轮子哥

**Comment by getActivity** [comment]
@Keeeya 小伙子，远程依赖发布了，后续留意下更新即可。

**Comment by Keeeya** [comment]
> @Keeeya 小伙子，远程依赖发布了，后续留意下更新即可。

好滴，多谢老哥
