### ISSUE TITLE
[Bug]：同时设置Toolbar和TitleBar Toolbar点击范围有问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [getActivity/TitleBar#66]
### 框架版本【必填】

10.3

### 问题描述【必填】

当同时设置了Toolbar和TitleBar，只设置leftview可以点击返回，但是整个Toolbar都可以点击，重叠之后就变成了只有左边返回按钮可以点击了😂

### 复现步骤【必填】

![image](https://github.com/getActivity/TitleBar/assets/54784104/3bf13215-0d1b-4df6-a523-449eb2bdc2c6)

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

一加七pro

### 出现问题的安卓版本【必填】

11

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

当前手机

### 框架最新的版本是否存在这个问题【必答】

是

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 是否有人曾提过类似的问题【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

否

### 使用原生的 FrameLayout 来实现是否也会出现该问题【必答】

否

### 提供截图或视频

![image](https://github.com/getActivity/TitleBar/assets/54784104/1995bd82-84f9-4695-af74-025114cabab2)

![image](https://github.com/getActivity/TitleBar/assets/54784104/12ec544b-a824-4be9-8b3c-58f5af9483e5)

**Comment by getActivity** [comment]
小伙子，我反复读了五六次问题描述，仍然没能理解你想要表达是什么，你直接提供一个可供复现的 Demo 工程过来，我来看一下。

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，我反复读了五六次问题描述，仍然没能理解你想要表达是什么，你直接提供一个可供复现的 Demo 工程过来，我来看一下。

emmm，我刚才写个demo，发现设置了titlebar的leftview点击事件之后，整个标题栏都会响应点击事件了😂要是用你的XCollapsingToolbarLayout代替官方那个，折叠起来标题栏之后就只有左侧会响应点击事件，下面这俩包的区别只是替换了折叠工具栏，你看看吧😂

[TitleBarDemo.zip](https://github.com/getActivity/TitleBar/files/11609827/TitleBarDemo.zip)


[TitleBarDemo (2).zip](https://github.com/getActivity/TitleBar/files/11609888/TitleBarDemo.2.zip)

**Comment by SaltedFish-Extreme** [comment]
我觉得设置了leftview的点击事件之后应该只有左侧能响应才对，不应该整个标题栏都能被点击

**Comment by getActivity** [comment]
https://github.com/getActivity/TitleBar/issues/65

**Comment by getActivity** [comment]
小伙子，我下载你的 Demo 后，发现你这个问题跟 https://github.com/getActivity/TitleBar/issues/65 是同一个问题，但是你没有认真看历史的 issue，如果有的话，你这个问题当天就能解决，而不是跟我 battle 一两天才能得到结果

**Comment by SaltedFish-Extreme** [comment]
> 小伙子，我下载你的 Demo 后，发现你这个问题跟 #65 是同一个问题，但是你没有认真看历史的 issue，如果有的话，你这个问题当天就能解决，而不是跟我 battle 一两天才能得到结果

好吧，其实我一开始看过那个，我以为他自定义样式跟我情况不大一样，虽然最后产生的效果是一样的，我就想另外开个issus提个问题😂

**Comment by getActivity** [comment]
@SaltedFish-Extreme 小伙子，远程依赖发布了，后续留意下更新即可。

**Comment by SaltedFish-Extreme** [comment]
好的，麻烦了😁
