### ISSUE TITLE
[疑惑]：setRightBackground 可以设置高度吗？

### ISSUE THREAD

**Issue by Mc-dashan** [getActivity/TitleBar#68]
### 问题描述【必填】

setRightBackground 的高度填充导航栏，有没有设置高度的方法呢，设置了setRightBackground后距离右侧没有边距

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 乱填 issue 问题

请重新提一个 issue 并纠正以上问题
