### ISSUE TITLE
页面设置了全屏，titleBar能否在状态栏下面显示，能否自动填充状态栏

### ISSUE THREAD

**Issue by Jasperben** [getActivity/TitleBar#69]
### 问题描述

页面设置了全屏，titleBar能否在状态栏下面显示，能否在布局中加入开关，设置是否自动填充状态栏高度

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
