### ISSUE TITLE
[建议]：关于 barStyle 属性的建议

### ISSUE THREAD

**Issue by moneeWong** [getActivity/TitleBar#70]
### 你觉得框架有什么不足之处？【必答】

对于 barStyle 属性目前的设计是内置了light，night，transparent，ripple四个样式，个人第一次使用的感觉是 ripple 与其他三个不是同一层面上的东西。其他三个偏向“主题”，而 ripple 偏向“点击效果”，他们实际上应该是有交集的，比如，我想要在暗色主题上使用 ripple 效果，目前的方式是无法做到的（当然不包括自己定义style），我只是感觉他们不应该归为一类。

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

可以将 barStyle 中的 ripple 拆分出来，只留下light，night，transparent三个主题，增加一个 selector 属性提供 none（无效果），normal（目前light中的点击效果），ripple（水波纹） 三种，来让开发者自己组合。因为是否使用点击效果还是要看app的设计风格的，这样可以让 barStyle（或者叫barTheme）的职责更明晰 ，又能组合出多个样式来满足更多的开发需求，以上是个人意见

**Comment by getActivity** [comment]
小伙子，实现你说按钮的水波纹效果，本质是设置 View 背景，目前有两种方式可以实现，一种是通过 xml，既可以在某个 xml 文件定死，又可以抽取成 xml style 样式然后再引用，第二种方式是设置全局的标题栏样式，并修改左右按钮的背景。

* 第一种方式

```xml
<com.hjq.bar.TitleBar
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:leftBackground="?attr/selectableItemBackgroundBorderless"
    app:title="默认的标题栏" />
```

* 第二种方式

```java
public class LightRippleBarStyle extends LightBarStyle {

    @Override
    public Drawable getLeftTitleBackground(Context context) {
        Drawable drawable = createRippleDrawable(context);
        if (drawable != null) {
            return drawable;
        }
        return super.getLeftTitleBackground(context);
    }

    @Override
    public Drawable getRightTitleBackground(Context context) {
        Drawable drawable = createRippleDrawable(context);
        if (drawable != null) {
            return drawable;
        }
        return super.getRightTitleBackground(context);
    }

    /**
     * 获取水波纹的点击效果
     */
    public Drawable createRippleDrawable(Context context) {
        TypedValue typedValue = new TypedValue();
        if (context.getTheme().resolveAttribute(android.R.attr.selectableItemBackgroundBorderless, typedValue, true)) {
            return TitleBarSupport.getDrawable(context, typedValue.resourceId);
        }
        return null;
    }
}
```

```java
// 初始化 TitleBar 默认样式
TitleBar.setDefaultStyle(new LightRippleBarStyle());
```

**Comment by moneeWong** [comment]
我明白我已经看过您的源码了，而我想表达的意思是，对于barStyle属性，ripple值与其他三个值不属于同一维度，是否考虑可以去掉，然后如果您想保留提供ripple效果，可以考虑增加新属性来供开发者选择而不是将它一并放在barStyle中，这只是我个人的看法，如果您觉得没有必要请忽略

**Comment by getActivity** [comment]
收到，多谢小伙子的建议。
